/*
 * IriusRisk API
 * Products API
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Reference;
import io.swagger.client.model.TestSource;
import io.swagger.client.model.Udt;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ControlTest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-26T11:09:51.654Z")
public class ControlTest {
  @SerializedName("expiryDate")
  private String expiryDate = null;

  @SerializedName("expiryPeriod")
  private Integer expiryPeriod = null;

  @SerializedName("steps")
  private String steps = null;

  @SerializedName("notes")
  private String notes = null;

  @SerializedName("source")
  private TestSource source = null;

  @SerializedName("references")
  private List<Reference> references = null;

  @SerializedName("udts")
  private List<Udt> udts = null;

  public ControlTest expiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @ApiModelProperty(value = "")
  public String getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
  }

  public ControlTest expiryPeriod(Integer expiryPeriod) {
    this.expiryPeriod = expiryPeriod;
    return this;
  }

   /**
   * Get expiryPeriod
   * @return expiryPeriod
  **/
  @ApiModelProperty(value = "")
  public Integer getExpiryPeriod() {
    return expiryPeriod;
  }

  public void setExpiryPeriod(Integer expiryPeriod) {
    this.expiryPeriod = expiryPeriod;
  }

  public ControlTest steps(String steps) {
    this.steps = steps;
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @ApiModelProperty(value = "")
  public String getSteps() {
    return steps;
  }

  public void setSteps(String steps) {
    this.steps = steps;
  }

  public ControlTest notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @ApiModelProperty(value = "")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public ControlTest source(TestSource source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @ApiModelProperty(value = "")
  public TestSource getSource() {
    return source;
  }

  public void setSource(TestSource source) {
    this.source = source;
  }

  public ControlTest references(List<Reference> references) {
    this.references = references;
    return this;
  }

  public ControlTest addReferencesItem(Reference referencesItem) {
    if (this.references == null) {
      this.references = new ArrayList<Reference>();
    }
    this.references.add(referencesItem);
    return this;
  }

   /**
   * Get references
   * @return references
  **/
  @ApiModelProperty(value = "")
  public List<Reference> getReferences() {
    return references;
  }

  public void setReferences(List<Reference> references) {
    this.references = references;
  }

  public ControlTest udts(List<Udt> udts) {
    this.udts = udts;
    return this;
  }

  public ControlTest addUdtsItem(Udt udtsItem) {
    if (this.udts == null) {
      this.udts = new ArrayList<Udt>();
    }
    this.udts.add(udtsItem);
    return this;
  }

   /**
   * Get udts
   * @return udts
  **/
  @ApiModelProperty(value = "")
  public List<Udt> getUdts() {
    return udts;
  }

  public void setUdts(List<Udt> udts) {
    this.udts = udts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControlTest controlTest = (ControlTest) o;
    return Objects.equals(this.expiryDate, controlTest.expiryDate) &&
        Objects.equals(this.expiryPeriod, controlTest.expiryPeriod) &&
        Objects.equals(this.steps, controlTest.steps) &&
        Objects.equals(this.notes, controlTest.notes) &&
        Objects.equals(this.source, controlTest.source) &&
        Objects.equals(this.references, controlTest.references) &&
        Objects.equals(this.udts, controlTest.udts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiryDate, expiryPeriod, steps, notes, source, references, udts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControlTest {\n");
    
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    expiryPeriod: ").append(toIndentedString(expiryPeriod)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    references: ").append(toIndentedString(references)).append("\n");
    sb.append("    udts: ").append(toIndentedString(udts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

