/*
 * IriusRisk API
 * Products API
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * JsonData12
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-26T11:09:51.654Z")
public class JsonData12 {
  @SerializedName("ref")
  private String ref = null;

  @SerializedName("mitigation")
  private Integer mitigation = null;

  public JsonData12 ref(String ref) {
    this.ref = ref;
    return this;
  }

   /**
   * Existing Countermeasure reference
   * @return ref
  **/
  @ApiModelProperty(value = "Existing Countermeasure reference")
  public String getRef() {
    return ref;
  }

  public void setRef(String ref) {
    this.ref = ref;
  }

  public JsonData12 mitigation(Integer mitigation) {
    this.mitigation = mitigation;
    return this;
  }

   /**
   * Mitigation
   * @return mitigation
  **/
  @ApiModelProperty(value = "Mitigation")
  public Integer getMitigation() {
    return mitigation;
  }

  public void setMitigation(Integer mitigation) {
    this.mitigation = mitigation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonData12 jsonData12 = (JsonData12) o;
    return Objects.equals(this.ref, jsonData12.ref) &&
        Objects.equals(this.mitigation, jsonData12.mitigation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ref, mitigation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonData12 {\n");
    
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    mitigation: ").append(toIndentedString(mitigation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

